### ISSUE TITLE
'Pause before Suspend' useless in some case

### ISSUE THREAD

**Issue by xzzpig** [popsUlfr/SDH-PauseGames#8]
I turn on both 'Pause before Suspend' and 'Pause on focus loss'.
When I suspend my steam deck ,It can be noticed that game music pause a little time then continue play, then deck suspend.
When I turn on only 'Pause before Suspend', it seems normal.
I'am using at version 0.4.1,decky version 2.5.4.

**Comment by Gwindalmir** [comment]
I couldn't get Pause Before Suspend to work at all.
I ended up enabling "Pause on Overlay" and then press the Steam button before sleeping. That works.

**Comment by popsUlfr** [comment]
Thanks for the report. If I'm not mistaken thinking about it logically, the focus change event seems to continue to trigger while the applications are getting suspended and thus undoing this.

**Comment by popsUlfr** [comment]
Hi @xzzpig @Gwindalmir , once the new plugin version hits the Testing repo and if you have some time could you kindly comment here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/274 on which Steam Client branch you currently are and if the fix works for you ? Thanks in advance.

**Comment by Gwindalmir** [comment]
> Hi @xzzpig @Gwindalmir , once the new plugin version hits the Testing repo and if you have some time could you kindly comment here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/274 on which Steam Client branch you currently are and if the fix works for you ? Thanks in advance.

Sure, I'll tell you now though that I'm on the steam beta branch, and the plugin UI doesn't work anymore. Just shows up as blank bars. Started a couple weeks ago. Most of the plugins I have are like that now. I guess there was some change that plugin authors need to implement. I don't know the details though.
I'll check the testing repo and report back though.

**Comment by popsUlfr** [comment]
@Gwindalmir Right, the plugins need to update the decky-frontend-lib dependency to work again with the latest beta. On my end I can confirm that the update makes the plugin usable again :)

**Comment by IBNobody** [comment]
@popsUlfr Is there a similar fix that could be done for resuming? When coming out of suspend, I find that the game music continues to play while Steam tries to connect back to the servers.
